// <auto-generated />
using System;
using MSNK.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MSNK.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211115044645_AddInitialTables")]
    partial class AddInitialTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MSNK.Models.Modules.AkAkaun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkCartaId1")
                        .HasColumnType("int");

                    b.Property<int>("AkCartaId2")
                        .HasColumnType("int");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KWId")
                        .HasColumnType("int");

                    b.Property<decimal>("Kredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoRujukan")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("Tarikh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AkCartaId1");

                    b.HasIndex("AkCartaId2");

                    b.HasIndex("KWId");

                    b.ToTable("AkAkaun");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkCartaId")
                        .HasColumnType("int");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("KWId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoAkaun")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AkCartaId");

                    b.HasIndex("BankId");

                    b.HasIndex("KWId");

                    b.ToTable("AkBank");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkCarta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Catatan1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Catatan2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DebitKredit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JenisId")
                        .HasColumnType("int");

                    b.Property<int>("KWId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Nama")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ParasId")
                        .HasColumnType("int");

                    b.Property<string>("UmumDetail")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("JenisId");

                    b.HasIndex("KWId");

                    b.HasIndex("ParasId");

                    b.ToTable("AkCarta");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkTerima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AkAkaunId")
                        .HasColumnType("int");

                    b.Property<int>("AkBankId")
                        .HasColumnType("int");

                    b.Property<string>("Alamat1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Alamat2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Alamat3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bandar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FlBatal")
                        .HasColumnType("int");

                    b.Property<int>("FlCetak")
                        .HasColumnType("int");

                    b.Property<int>("FlPosting")
                        .HasColumnType("int");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KWId")
                        .HasColumnType("int");

                    b.Property<string>("KodPembayar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NegeriId")
                        .HasColumnType("int");

                    b.Property<string>("NoKp")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NoRujukan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poskod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sebab")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Tahun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarikh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AkAkaunId");

                    b.HasIndex("AkBankId");

                    b.HasIndex("KWId");

                    b.HasIndex("NegeriId");

                    b.ToTable("AkTerima");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkTerima1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkCartaId")
                        .HasColumnType("int");

                    b.Property<int>("AkTerimaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amaun")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AkCartaId");

                    b.HasIndex("AkTerimaId");

                    b.ToTable("AkTerima1");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkTerima2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkTerimaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amaun")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CaraBayarId")
                        .HasColumnType("int");

                    b.Property<string>("JenisCek")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("KodBankCek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoCek")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NoSlip")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("TarSlip")
                        .HasColumnType("datetime2");

                    b.Property<string>("TempatCek")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AkTerimaId");

                    b.HasIndex("CaraBayarId");

                    b.ToTable("AkTerima2");
                });

            modelBuilder.Entity("MSNK.Models.Modules.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Bank");
                });

            modelBuilder.Entity("MSNK.Models.Modules.CaraBayar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Perihal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CaraBayar");
                });

            modelBuilder.Entity("MSNK.Models.Modules.Jenis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jenis");
                });

            modelBuilder.Entity("MSNK.Models.Modules.KW", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Perihal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("KW");
                });

            modelBuilder.Entity("MSNK.Models.Modules.Modul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FuncId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FuncName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Modul");
                });

            modelBuilder.Entity("MSNK.Models.Modules.Negeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Perihal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Negeri");
                });

            modelBuilder.Entity("MSNK.Models.Modules.PO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Batal")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KWId")
                        .HasColumnType("int");

                    b.Property<string>("NoPO")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PembekalId")
                        .HasColumnType("int");

                    b.Property<string>("Posting")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Tahun")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("Tarikh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarikhPosting")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KWId");

                    b.HasIndex("PembekalId");

                    b.ToTable("PO");
                });

            modelBuilder.Entity("MSNK.Models.Modules.PO1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amaun")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Bil")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Indek")
                        .HasColumnType("int");

                    b.Property<decimal>("Kuantiti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoStok")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("POId")
                        .HasColumnType("int");

                    b.Property<string>("Perihal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("POId");

                    b.ToTable("PO1");
                });

            modelBuilder.Entity("MSNK.Models.Modules.PO2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkCartaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amaun")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KWId")
                        .HasColumnType("int");

                    b.Property<int>("POId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AkCartaId");

                    b.HasIndex("KWId");

                    b.HasIndex("POId");

                    b.ToTable("PO2");
                });

            modelBuilder.Entity("MSNK.Models.Modules.Paras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Paras");
                });

            modelBuilder.Entity("MSNK.Models.Modules.Pembekal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkBankId")
                        .HasColumnType("int");

                    b.Property<string>("AkaunBank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Alamat1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Alamat2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Alamat3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bandar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Emel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KodSykt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NamaSykt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NegeriId")
                        .HasColumnType("int");

                    b.Property<string>("NoPendaftaran")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Poskod")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Telefon1")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AkBankId");

                    b.HasIndex("NegeriId");

                    b.ToTable("Pembekal");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MSNK.Models.Administration.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkAkaun", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkCarta", "AkCarta1")
                        .WithMany("AkAkaun1")
                        .HasForeignKey("AkCartaId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.AkCarta", "AkCarta2")
                        .WithMany("AkAkaun2")
                        .HasForeignKey("AkCartaId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.KW", "KW")
                        .WithMany("AkAkaun")
                        .HasForeignKey("KWId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AkCarta1");

                    b.Navigation("AkCarta2");

                    b.Navigation("KW");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkBank", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkCarta", "AkCarta")
                        .WithMany("AkBank")
                        .HasForeignKey("AkCartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.Bank", "Bank")
                        .WithMany("AkBank")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.KW", "KW")
                        .WithMany("AkBank")
                        .HasForeignKey("KWId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AkCarta");

                    b.Navigation("Bank");

                    b.Navigation("KW");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkCarta", b =>
                {
                    b.HasOne("MSNK.Models.Modules.Jenis", "Jenis")
                        .WithMany("AkCarta")
                        .HasForeignKey("JenisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.KW", "KW")
                        .WithMany("AkCarta")
                        .HasForeignKey("KWId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.Paras", "Paras")
                        .WithMany("AkCarta")
                        .HasForeignKey("ParasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jenis");

                    b.Navigation("KW");

                    b.Navigation("Paras");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkTerima", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkAkaun", null)
                        .WithMany("AkTerima")
                        .HasForeignKey("AkAkaunId");

                    b.HasOne("MSNK.Models.Modules.AkBank", "AkBank")
                        .WithMany("AkTerima")
                        .HasForeignKey("AkBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.KW", "KW")
                        .WithMany("AkTerima")
                        .HasForeignKey("KWId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.Negeri", "Negeri")
                        .WithMany("AkTerima")
                        .HasForeignKey("NegeriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AkBank");

                    b.Navigation("KW");

                    b.Navigation("Negeri");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkTerima1", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkCarta", "AkCarta")
                        .WithMany("AkTerima1")
                        .HasForeignKey("AkCartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.AkTerima", "AkTerima")
                        .WithMany("AkTerima1")
                        .HasForeignKey("AkTerimaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AkCarta");

                    b.Navigation("AkTerima");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkTerima2", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkTerima", "AkTerima")
                        .WithMany("AkTerima2")
                        .HasForeignKey("AkTerimaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.CaraBayar", "CaraBayar")
                        .WithMany("akTerima2")
                        .HasForeignKey("CaraBayarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AkTerima");

                    b.Navigation("CaraBayar");
                });

            modelBuilder.Entity("MSNK.Models.Modules.PO", b =>
                {
                    b.HasOne("MSNK.Models.Modules.KW", "KW")
                        .WithMany("PO")
                        .HasForeignKey("KWId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.Pembekal", "Pembekal")
                        .WithMany("PO")
                        .HasForeignKey("PembekalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KW");

                    b.Navigation("Pembekal");
                });

            modelBuilder.Entity("MSNK.Models.Modules.PO1", b =>
                {
                    b.HasOne("MSNK.Models.Modules.PO", "PO")
                        .WithMany("PO1")
                        .HasForeignKey("POId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PO");
                });

            modelBuilder.Entity("MSNK.Models.Modules.PO2", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkCarta", "AkCarta")
                        .WithMany("PO2")
                        .HasForeignKey("AkCartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.KW", "KW")
                        .WithMany("PO2")
                        .HasForeignKey("KWId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.PO", "PO")
                        .WithMany("PO2")
                        .HasForeignKey("POId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AkCarta");

                    b.Navigation("KW");

                    b.Navigation("PO");
                });

            modelBuilder.Entity("MSNK.Models.Modules.Pembekal", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkBank", "AkBank")
                        .WithMany("Pembekal")
                        .HasForeignKey("AkBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.Negeri", "Negeri")
                        .WithMany("Pembekal")
                        .HasForeignKey("NegeriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AkBank");

                    b.Navigation("Negeri");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkAkaun", b =>
                {
                    b.Navigation("AkTerima");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkBank", b =>
                {
                    b.Navigation("AkTerima");

                    b.Navigation("Pembekal");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkCarta", b =>
                {
                    b.Navigation("AkAkaun1");

                    b.Navigation("AkAkaun2");

                    b.Navigation("AkBank");

                    b.Navigation("AkTerima1");

                    b.Navigation("PO2");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkTerima", b =>
                {
                    b.Navigation("AkTerima1");

                    b.Navigation("AkTerima2");
                });

            modelBuilder.Entity("MSNK.Models.Modules.Bank", b =>
                {
                    b.Navigation("AkBank");
                });

            modelBuilder.Entity("MSNK.Models.Modules.CaraBayar", b =>
                {
                    b.Navigation("akTerima2");
                });

            modelBuilder.Entity("MSNK.Models.Modules.Jenis", b =>
                {
                    b.Navigation("AkCarta");
                });

            modelBuilder.Entity("MSNK.Models.Modules.KW", b =>
                {
                    b.Navigation("AkAkaun");

                    b.Navigation("AkBank");

                    b.Navigation("AkCarta");

                    b.Navigation("AkTerima");

                    b.Navigation("PO");

                    b.Navigation("PO2");
                });

            modelBuilder.Entity("MSNK.Models.Modules.Negeri", b =>
                {
                    b.Navigation("AkTerima");

                    b.Navigation("Pembekal");
                });

            modelBuilder.Entity("MSNK.Models.Modules.PO", b =>
                {
                    b.Navigation("PO1");

                    b.Navigation("PO2");
                });

            modelBuilder.Entity("MSNK.Models.Modules.Paras", b =>
                {
                    b.Navigation("AkCarta");
                });

            modelBuilder.Entity("MSNK.Models.Modules.Pembekal", b =>
                {
                    b.Navigation("PO");
                });
#pragma warning restore 612, 618
        }
    }
}
