// <auto-generated />
using System;
using MSNK.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MSNK.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MSNK.Models.Modules.AkAkaun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkCartaId1")
                        .HasColumnType("int");

                    b.Property<int>("AkCartaId2")
                        .HasColumnType("int");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("JKWId")
                        .HasColumnType("int");

                    b.Property<decimal>("Kredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoRujukan")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("Tarikh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AkCartaId1");

                    b.HasIndex("AkCartaId2");

                    b.HasIndex("JKWId");

                    b.ToTable("AkAkaun");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkCartaId")
                        .HasColumnType("int");

                    b.Property<int>("JBankId")
                        .HasColumnType("int");

                    b.Property<int>("JKWId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("NoAkaun")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AkCartaId");

                    b.HasIndex("JBankId");

                    b.HasIndex("JKWId");

                    b.ToTable("AkBank");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkBelian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkBankId")
                        .HasColumnType("int");

                    b.Property<int?>("AkPOId")
                        .HasColumnType("int");

                    b.Property<int>("AkPembekalId")
                        .HasColumnType("int");

                    b.Property<int>("FlBatal")
                        .HasColumnType("int");

                    b.Property<int>("FlCetak")
                        .HasColumnType("int");

                    b.Property<int>("FlPosting")
                        .HasColumnType("int");

                    b.Property<string>("FlTanggungan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JKWId")
                        .HasColumnType("int");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoInbois")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tahun")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarikh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarikhPosting")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AkBankId");

                    b.HasIndex("AkPOId");

                    b.HasIndex("AkPembekalId");

                    b.HasIndex("JKWId");

                    b.ToTable("AkBelian");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkBelian1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkBelianId")
                        .HasColumnType("int");

                    b.Property<int>("AkCartaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amaun")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AkBelianId");

                    b.HasIndex("AkCartaId");

                    b.ToTable("AkBelian1");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkBelian2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkBelianId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amaun")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Baris")
                        .HasColumnType("int");

                    b.Property<string>("Bil")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Indek")
                        .HasColumnType("int");

                    b.Property<decimal>("Kuantiti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoStok")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Perihal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AkBelianId");

                    b.ToTable("AkBelian2");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkCarta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Baki")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Catatan1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Catatan2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DebitKredit")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("JJenisId")
                        .HasColumnType("int");

                    b.Property<int>("JKWId")
                        .HasColumnType("int");

                    b.Property<int>("JParasId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Perihal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<string>("UmumDetail")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JJenisId");

                    b.HasIndex("JKWId");

                    b.HasIndex("JParasId");

                    b.ToTable("AkCarta");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkJurnal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Batal")
                        .HasColumnType("int");

                    b.Property<string>("Catatan1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Catatan2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Catatan3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Catatan4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Cetak")
                        .HasColumnType("int");

                    b.Property<int>("JKWId")
                        .HasColumnType("int");

                    b.Property<decimal>("JumDebit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("JumKredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoJurnal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Posting")
                        .HasColumnType("int");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarikh")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JKWId");

                    b.ToTable("AkJurnal");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkJurnal1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkCartaId")
                        .HasColumnType("int");

                    b.Property<int>("AkJurnalId")
                        .HasColumnType("int");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Indeks")
                        .HasColumnType("int");

                    b.Property<decimal>("Kredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AkCartaId");

                    b.HasIndex("AkJurnalId");

                    b.ToTable("AkJurnal1");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkPO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkPembekalId")
                        .HasColumnType("int");

                    b.Property<int>("FlBatal")
                        .HasColumnType("int");

                    b.Property<int>("FlPosting")
                        .HasColumnType("int");

                    b.Property<int>("JKWId")
                        .HasColumnType("int");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoPO")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tahun")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarikh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarikhPosting")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AkPembekalId");

                    b.HasIndex("JKWId");

                    b.ToTable("AkPO");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkPO1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkCartaId")
                        .HasColumnType("int");

                    b.Property<int>("AkPOId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amaun")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("JKWId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AkCartaId");

                    b.HasIndex("AkPOId");

                    b.HasIndex("JKWId");

                    b.ToTable("AkPO1");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkPO2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkPOId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amaun")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Baris")
                        .HasColumnType("int");

                    b.Property<string>("Bil")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Indek")
                        .HasColumnType("int");

                    b.Property<decimal>("Kuantiti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoStok")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Perihal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AkPOId");

                    b.ToTable("AkPO2");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkPembekal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AkaunBank")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Alamat1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Alamat2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Alamat3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bandar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Emel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("JBankId")
                        .HasColumnType("int");

                    b.Property<int>("JNegeriId")
                        .HasColumnType("int");

                    b.Property<string>("KodSykt")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("NamaSykt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoPendaftaran")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Poskod")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JBankId");

                    b.HasIndex("JNegeriId");

                    b.ToTable("AkPembekal");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkTerima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AkAkaunId")
                        .HasColumnType("int");

                    b.Property<int>("AkBankId")
                        .HasColumnType("int");

                    b.Property<string>("Alamat1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Alamat2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Alamat3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bandar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Emel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FlBatal")
                        .HasColumnType("int");

                    b.Property<int>("FlCetak")
                        .HasColumnType("int");

                    b.Property<int>("FlPosting")
                        .HasColumnType("int");

                    b.Property<int>("JKWId")
                        .HasColumnType("int");

                    b.Property<int>("JNegeriId")
                        .HasColumnType("int");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KodPembayar")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoKp")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NoRujukan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Poskod")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Sebab")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Tahun")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarikh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarikhPosting")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tel")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AkAkaunId");

                    b.HasIndex("AkBankId");

                    b.HasIndex("JKWId");

                    b.HasIndex("JNegeriId");

                    b.ToTable("AkTerima");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkTerima1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkCartaId")
                        .HasColumnType("int");

                    b.Property<int>("AkTerimaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amaun")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AkCartaId");

                    b.HasIndex("AkTerimaId");

                    b.ToTable("AkTerima1");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkTerima2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AkTerimaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amaun")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("JCaraBayarId")
                        .HasColumnType("int");

                    b.Property<string>("JenisCek")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("KodBankCek")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("NoCek")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NoSlip")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarSlip")
                        .HasColumnType("datetime2");

                    b.Property<string>("TempatCek")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AkTerimaId");

                    b.HasIndex("JCaraBayarId");

                    b.ToTable("AkTerima2");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AppLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LgDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LgModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LgNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LgOperation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoRujukan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SysCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppLog");
                });

            modelBuilder.Entity("MSNK.Models.Modules.JBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("KodEFT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JBank");
                });

            modelBuilder.Entity("MSNK.Models.Modules.JCaraBayar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Perihal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JCaraBayar");
                });

            modelBuilder.Entity("MSNK.Models.Modules.JJenis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JJenis");
                });

            modelBuilder.Entity("MSNK.Models.Modules.JKW", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Perihal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JKW");
                });

            modelBuilder.Entity("MSNK.Models.Modules.JNegeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Perihal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TarKemaskini")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarMasuk")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdKemaskini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JNegeri");
                });

            modelBuilder.Entity("MSNK.Models.Modules.JParas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JParas");
                });

            modelBuilder.Entity("MSNK.Models.Modules.SiModul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FuncId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FuncName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SiModul");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MSNK.Models.Administration.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkAkaun", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkCarta", "AkCarta1")
                        .WithMany("AkAkaun1")
                        .HasForeignKey("AkCartaId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.AkCarta", "AkCarta2")
                        .WithMany("AkAkaun2")
                        .HasForeignKey("AkCartaId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.JKW", "JKW")
                        .WithMany("AkAkaun")
                        .HasForeignKey("JKWId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AkCarta1");

                    b.Navigation("AkCarta2");

                    b.Navigation("JKW");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkBank", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkCarta", "AkCarta")
                        .WithMany("AkBank")
                        .HasForeignKey("AkCartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.JBank", "JBank")
                        .WithMany("AkBank")
                        .HasForeignKey("JBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.JKW", "JKW")
                        .WithMany("AkBank")
                        .HasForeignKey("JKWId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AkCarta");

                    b.Navigation("JBank");

                    b.Navigation("JKW");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkBelian", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkBank", "AkBank")
                        .WithMany("AkBelian")
                        .HasForeignKey("AkBankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.AkPO", "AkPO")
                        .WithMany("AkBelian")
                        .HasForeignKey("AkPOId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MSNK.Models.Modules.AkPembekal", "AkPembekal")
                        .WithMany("AkBelian")
                        .HasForeignKey("AkPembekalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.JKW", "JKW")
                        .WithMany("AkBelian")
                        .HasForeignKey("JKWId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AkBank");

                    b.Navigation("AkPembekal");

                    b.Navigation("AkPO");

                    b.Navigation("JKW");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkBelian1", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkBelian", null)
                        .WithMany("AkBelian1")
                        .HasForeignKey("AkBelianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.AkCarta", "AkCarta")
                        .WithMany("AkBelian1")
                        .HasForeignKey("AkCartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AkCarta");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkBelian2", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkBelian", null)
                        .WithMany("AkBelian2")
                        .HasForeignKey("AkBelianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkCarta", b =>
                {
                    b.HasOne("MSNK.Models.Modules.JJenis", "JJenis")
                        .WithMany("AkCarta")
                        .HasForeignKey("JJenisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.JKW", "JKW")
                        .WithMany("AkCarta")
                        .HasForeignKey("JKWId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.JParas", "JParas")
                        .WithMany("AkCarta")
                        .HasForeignKey("JParasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JJenis");

                    b.Navigation("JKW");

                    b.Navigation("JParas");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkJurnal", b =>
                {
                    b.HasOne("MSNK.Models.Modules.JKW", "JKW")
                        .WithMany("AkJurnal")
                        .HasForeignKey("JKWId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JKW");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkJurnal1", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkCarta", "AkCarta")
                        .WithMany("AkJurnal1")
                        .HasForeignKey("AkCartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.AkJurnal", null)
                        .WithMany("AkJurnal1")
                        .HasForeignKey("AkJurnalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AkCarta");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkPO", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkPembekal", "AkPembekal")
                        .WithMany("AkPO")
                        .HasForeignKey("AkPembekalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.JKW", "JKW")
                        .WithMany("AkPO")
                        .HasForeignKey("JKWId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AkPembekal");

                    b.Navigation("JKW");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkPO1", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkCarta", "AkCarta")
                        .WithMany("AkPO1")
                        .HasForeignKey("AkCartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.AkPO", "AkPO")
                        .WithMany("AkPO1")
                        .HasForeignKey("AkPOId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.JKW", null)
                        .WithMany("AkPO1")
                        .HasForeignKey("JKWId");

                    b.Navigation("AkCarta");

                    b.Navigation("AkPO");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkPO2", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkPO", "AkPO")
                        .WithMany("AkPO2")
                        .HasForeignKey("AkPOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AkPO");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkPembekal", b =>
                {
                    b.HasOne("MSNK.Models.Modules.JBank", "JBank")
                        .WithMany("AkPembekal")
                        .HasForeignKey("JBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.JNegeri", "JNegeri")
                        .WithMany("AkPembekal")
                        .HasForeignKey("JNegeriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JBank");

                    b.Navigation("JNegeri");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkTerima", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkAkaun", null)
                        .WithMany("AkTerima")
                        .HasForeignKey("AkAkaunId");

                    b.HasOne("MSNK.Models.Modules.AkBank", "AkBank")
                        .WithMany("AkTerima")
                        .HasForeignKey("AkBankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.JKW", "JKW")
                        .WithMany("AkTerima")
                        .HasForeignKey("JKWId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.JNegeri", "JNegeri")
                        .WithMany("AkTerima")
                        .HasForeignKey("JNegeriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AkBank");

                    b.Navigation("JKW");

                    b.Navigation("JNegeri");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkTerima1", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkCarta", "AkCarta")
                        .WithMany("AkTerima1")
                        .HasForeignKey("AkCartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.AkTerima", null)
                        .WithMany("AkTerima1")
                        .HasForeignKey("AkTerimaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AkCarta");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkTerima2", b =>
                {
                    b.HasOne("MSNK.Models.Modules.AkTerima", null)
                        .WithMany("AkTerima2")
                        .HasForeignKey("AkTerimaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSNK.Models.Modules.JCaraBayar", "JCaraBayar")
                        .WithMany("akTerima2")
                        .HasForeignKey("JCaraBayarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JCaraBayar");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkAkaun", b =>
                {
                    b.Navigation("AkTerima");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkBank", b =>
                {
                    b.Navigation("AkBelian");

                    b.Navigation("AkTerima");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkBelian", b =>
                {
                    b.Navigation("AkBelian1");

                    b.Navigation("AkBelian2");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkCarta", b =>
                {
                    b.Navigation("AkAkaun1");

                    b.Navigation("AkAkaun2");

                    b.Navigation("AkBank");

                    b.Navigation("AkBelian1");

                    b.Navigation("AkJurnal1");

                    b.Navigation("AkPO1");

                    b.Navigation("AkTerima1");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkJurnal", b =>
                {
                    b.Navigation("AkJurnal1");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkPO", b =>
                {
                    b.Navigation("AkBelian");

                    b.Navigation("AkPO1");

                    b.Navigation("AkPO2");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkPembekal", b =>
                {
                    b.Navigation("AkBelian");

                    b.Navigation("AkPO");
                });

            modelBuilder.Entity("MSNK.Models.Modules.AkTerima", b =>
                {
                    b.Navigation("AkTerima1");

                    b.Navigation("AkTerima2");
                });

            modelBuilder.Entity("MSNK.Models.Modules.JBank", b =>
                {
                    b.Navigation("AkBank");

                    b.Navigation("AkPembekal");
                });

            modelBuilder.Entity("MSNK.Models.Modules.JCaraBayar", b =>
                {
                    b.Navigation("akTerima2");
                });

            modelBuilder.Entity("MSNK.Models.Modules.JJenis", b =>
                {
                    b.Navigation("AkCarta");
                });

            modelBuilder.Entity("MSNK.Models.Modules.JKW", b =>
                {
                    b.Navigation("AkAkaun");

                    b.Navigation("AkBank");

                    b.Navigation("AkBelian");

                    b.Navigation("AkCarta");

                    b.Navigation("AkJurnal");

                    b.Navigation("AkPO");

                    b.Navigation("AkPO1");

                    b.Navigation("AkTerima");
                });

            modelBuilder.Entity("MSNK.Models.Modules.JNegeri", b =>
                {
                    b.Navigation("AkPembekal");

                    b.Navigation("AkTerima");
                });

            modelBuilder.Entity("MSNK.Models.Modules.JParas", b =>
                {
                    b.Navigation("AkCarta");
                });
#pragma warning restore 612, 618
        }
    }
}
